name: Test deploy                    # Workflow 이름
on:                                  # Event 감지
  push:
    branches:
      - main                        
jobs:                                # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.   # Repo checkout
        uses: actions/checkout@v3
      
      - name: Check Node v            # Node v 확인
        run: node -v
        
      - name: Install dependencies    # 의존 파일 설치
        run: npm install
      
      - name: Generate build          # React Build
        run: CI='false' npm run build
      
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "build/"
          target: ${{ secrets.TARGET_PATH }}
